program test_cross_framework
    !! BO6: FortBO's posterior and acquisition against two outside references.
    !!
    !! The roadmap asks for a benchmark against BoTorch/GPyTorch, JAX, and
    !! deterministic NumPy on matched functions, models, precision, seeds,
    !! restart counts, and stopping criteria, reporting regret and sample
    !! efficiency separately from wall time. This file is the **correctness**
    !! half, and it is deliberately first: a speed number from a build whose
    !! posterior is wrong is worse than no number at all, because it looks like
    !! evidence.
    !!
    !! What "matched" had to mean here, and what it cost:
    !!
    !!   * **The model is pinned, not fitted.** Fitting hyperparameters on each
    !!     side would compare two optimizers and report the difference as a
    !!     modelling discrepancy. Everything that could differ — kernel,
    !!     lengthscale, signal variance, noise, observations, query points,
    !!     precision — is stated.
    !!   * **The hyperparameters are GPyTorch's, not the ones it was asked
    !!     for.** GPyTorch stores constrained parameters through a softplus
    !!     whose inverse is evaluated in single precision, so assigning a
    !!     float64 lengthscale of 0.7 stores something about 1.2e-8 away. That
    !!     was measured, not assumed, and it accounted exactly for an earlier
    !!     2e-9 disagreement. Loosening the gate to absorb it would have hidden
    !!     a real effect; using what GPyTorch actually holds removes it, and the
    !!     posterior now agrees to 7e-16.
    !!   * **Two references, not one.** GPyTorch's agreement is strong evidence
    !!     because it is mature; NumPy's is evidence of a *different* kind,
    !!     because it computes the closed forms directly from the definitions
    !!     and a shared misunderstanding between two GP libraries would not
    !!     survive it. The generator cross-checks the two against each other
    !!     before either reaches this file.
    !!
    !! The fixture is generated by `fortbo-bench/scripts/emit_reference.py` and
    !! checked in. A missing fixture is a **failure**, not a skip: a suite that
    !! silently passes when its reference data is absent is the exact shape of a
    !! cross-framework check that never actually ran.

    use fortnum_kinds, only: dp
    use fortnum_status, only: fortnum_status_t, FORTNUM_OK
    use fortml_kernels, only: kernel_t, make_rbf_kernel
    use fortml_gaussian_process, only: gp_regression_t
    use fortbo_acquisition, only: fortbo_expected_improvement
    implicit none

    integer :: failures

    failures = 0
    call check_against_the_references(failures)

    if (failures == 0) then
        print *, "test_cross_framework: PASS"
    else
        print *, "test_cross_framework: FAIL", failures
        error stop 1
    end if

contains

    subroutine check_against_the_references(failures)
        integer, intent(inout) :: failures
        type(fortnum_status_t) :: status
        type(gp_regression_t) :: model
        type(kernel_t) :: kernel
        real(dp) :: lengthscale, signal_variance, noise_variance, xi
        real(dp), allocatable :: train_x(:, :), train_y(:, :), query(:, :)
        real(dp), allocatable :: reference_mean(:), reference_sd(:)
        real(dp), allocatable :: reference_ei(:)
        real(dp), allocatable :: mean(:, :), variance(:)
        real(dp) :: best, sd, ei, worst_mean, worst_sd, worst_ei
        integer :: n_train, n_query, k, unit, ios
        character(len=256) :: path
        logical :: present_on_disk

        path = "test/fixtures/reference_gp.txt"
        inquire (file=path, exist=present_on_disk)
        if (.not. present_on_disk) then
            ! Not a skip. A cross-framework check that quietly passes with no
            ! reference data is indistinguishable from one that works.
            print *, "  FAIL: the reference fixture is missing; regenerate it "// &
                "with fortbo-bench/scripts/emit_reference.py"
            failures = failures + 1
            return
        end if

        open (newunit=unit, file=path, status="old", action="read", iostat=ios)
        if (ios /= 0) then
            print *, "  FAIL: the reference fixture could not be opened"
            failures = failures + 1
            return
        end if

        call skip_comments(unit)
        read (unit, *) lengthscale, signal_variance, noise_variance, xi
        call skip_comments(unit)
        read (unit, *) n_train, n_query

        allocate (train_x(n_train, 1), train_y(n_train, 1), query(n_query, 1))
        allocate (reference_mean(n_query), reference_sd(n_query))
        allocate (reference_ei(n_query))

        call read_block(unit, train_x(:, 1), n_train)
        call read_block(unit, train_y(:, 1), n_train)
        call read_block(unit, query(:, 1), n_query)
        call read_block(unit, reference_mean, n_query)
        call read_block(unit, reference_sd, n_query)
        call read_block(unit, reference_ei, n_query)
        close (unit)

        ! The same model, stated rather than learned.
        kernel = make_rbf_kernel(1, signal_variance, lengthscale, status)
        call expect(status%code == FORTNUM_OK, "the pinned kernel builds", &
            failures)

        ! Jitter zero, explicitly. FortML defaults to adding 1e-10 to the
        ! diagonal for conditioning, and the references add nothing. That
        ! default is invisible when a GP is checked against itself, but it is a
        ! genuine difference in the model being compared: it showed up here as a
        ! 2e-10 gap in the posterior standard deviation -- far too large for
        ! rounding and far too small to look like a bug. With a noise variance
        ! of 0.05 the Gram matrix is well conditioned without it, so nothing is
        ! traded away by matching the references exactly.
        call model%fit(train_x, train_y, kernel, noise_variance, status, &
            jitter=0.0_dp)
        call expect(status%code == FORTNUM_OK, "the GP conditions on the "// &
            "reference observations", failures)
        if (status%code /= FORTNUM_OK) return

        allocate (mean(n_query, 1), variance(n_query))
        call model%predict(query, mean, variance, status)
        call expect(status%code == FORTNUM_OK, "the posterior evaluates at the "// &
            "reference query points", failures)
        if (status%code /= FORTNUM_OK) return

        ! FortBO minimizes, so improvement is over the smallest observation --
        ! the same convention the generator negated BoTorch into.
        best = minval(train_y(:, 1))

        worst_mean = 0.0_dp
        worst_sd = 0.0_dp
        worst_ei = 0.0_dp
        do k = 1, n_query
            sd = sqrt(max(variance(k), 0.0_dp))
            call fortbo_expected_improvement(mean(k, 1), sd, best, xi, ei)
            worst_mean = max(worst_mean, abs(mean(k, 1) - reference_mean(k)))
            worst_sd = max(worst_sd, abs(sd - reference_sd(k)))
            worst_ei = max(worst_ei, abs(ei - reference_ei(k)))
        end do

        ! The posterior is the same closed form in every implementation, so it
        ! agrees to accumulated rounding over a six-point Cholesky and nothing
        ! more. A tolerance loose enough to hide a modelling difference would
        ! defeat the purpose of running the comparison.
        call expect(worst_mean < 1.0e-12_dp, &
            "the posterior mean matches the references to rounding", failures)
        call expect(worst_sd < 1.0e-12_dp, &
            "the posterior standard deviation matches to rounding", failures)
        ! Expected improvement additionally goes through erf, whose last bits
        ! differ between libm implementations.
        call expect(worst_ei < 1.0e-12_dp, &
            "expected improvement matches the references", failures)

        print *, "  posterior mean   max |diff| =", worst_mean
        print *, "  posterior sd     max |diff| =", worst_sd
        print *, "  expected improv. max |diff| =", worst_ei
    end subroutine check_against_the_references

    !! Advance past comment lines, which carry the provenance of each block.
    subroutine skip_comments(unit)
        integer, intent(in) :: unit
        character(len=256) :: line
        integer :: ios

        do
            read (unit, "(a)", iostat=ios) line
            if (ios /= 0) return
            if (len_trim(line) == 0) cycle
            if (line(1:1) == "#") cycle
            backspace (unit)
            return
        end do
    end subroutine skip_comments

    subroutine read_block(unit, values, n)
        integer, intent(in) :: unit
        real(dp), intent(out) :: values(:)
        integer, intent(in) :: n
        integer :: k

        call skip_comments(unit)
        do k = 1, n
            read (unit, *) values(k)
        end do
    end subroutine read_block

    subroutine expect(condition, description, failures)
        logical, intent(in) :: condition
        character(len=*), intent(in) :: description
        integer, intent(inout) :: failures

        if (.not. condition) then
            failures = failures + 1
            print *, "  FAIL: ", description
        end if
    end subroutine expect

end program test_cross_framework
